import {
  AuditOverview,
  AuditArea,
  ProgressBreakdown,
  Deadline,
  ActivityItem,
} from "./types";

export const clients = [
  "Acme Corporation",
  "Tech Innovations Inc",
  "Global Finance Ltd",
  "Retail Solutions Co",
  "Manufacturing Plus",
];

export const auditOverview: AuditOverview = {
  clientName: "Acme Corporation",
  financialYear: "2024",
  engagementStatus: "Active",
  engagementPartner: "Sarah Johnson",
  auditManager: "Michael Chen",
  overallProgress: 42,
  startDate: "2026-07-01",
  dueDate: "2026-08-15",
};

export const auditAreas: AuditArea[] = [
  {
    id: "revenue",
    name: "Revenue",
    risk: "High",
    progress: 45,
    assignedAuditor: { id: "a1", name: "Emma Wilson", avatar: "EW" },
    tasks: [
      { id: "t1", title: "Analyze revenue transactions", status: "Open" },
      { id: "t2", title: "Review sales agreements", status: "Open" },
      { id: "t3", title: "Test revenue cutoff", status: "In Progress" },
      { id: "t4", title: "Verify customer credits", status: "Open" },
      { id: "t5", title: "Check revenue recognition", status: "Open" },
      { id: "t6", title: "Review accruals", status: "In Progress" },
      { id: "t7", title: "Test invoice accuracy", status: "Open" },
      { id: "t8", title: "Verify pricing policies", status: "Open" },
    ],
    evidence: [
      { id: "e1", title: "Revenue GL details", status: "Open" },
      { id: "e2", title: "Sales journal entries", status: "Open" },
      { id: "e3", title: "Customer contracts", status: "In Progress" },
      { id: "e4", title: "Credit memos", status: "Open" },
      { id: "e5", title: "Revenue policies", status: "Open" },
      { id: "e6", title: "Cutoff tests", status: "Open" },
      { id: "e7", title: "Pricing schedules", status: "In Progress" },
      { id: "e8", title: "Accrual analysis", status: "Open" },
      { id: "e9", title: "Incentives documentation", status: "Open" },
      { id: "e10", title: "Revenue contracts", status: "Open" },
      { id: "e11", title: "Invoice samples", status: "In Progress" },
      { id: "e12", title: "Sales discounts", status: "Open" },
    ],
    status: "In Progress",
    client: "Acme Corporation",
  },
  {
    id: "cash-bank",
    name: "Cash & Bank",
    risk: "High",
    progress: 72,
    assignedAuditor: { id: "a2", name: "David Martinez", avatar: "DM" },
    tasks: [
      { id: "t1", title: "Reconcile bank accounts", status: "Completed" },
      { id: "t2", title: "Test cash controls", status: "Open" },
      { id: "t3", title: "Review bank confirmations", status: "Open" },
    ],
    evidence: [
      { id: "e1", title: "Bank statements", status: "Completed" },
      { id: "e2", title: "Reconciliations", status: "Completed" },
      { id: "e3", title: "Bank confirmations", status: "Open" },
      { id: "e4", title: "Deposit slips", status: "Open" },
      { id: "e5", title: "Cash counts", status: "Open" },
    ],
    status: "Review",
    client: "Acme Corporation",
  },
  {
    id: "payroll",
    name: "Payroll",
    risk: "Medium",
    progress: 85,
    assignedAuditor: { id: "a3", name: "Lisa Anderson", avatar: "LA" },
    tasks: [
      { id: "t1", title: "Test payroll processing", status: "Completed" },
      { id: "t2", title: "Review tax withholdings", status: "Completed" },
    ],
    evidence: [
      { id: "e1", title: "Payroll registers", status: "Completed" },
      { id: "e2", title: "Tax filings", status: "Completed" },
    ],
    status: "Review",
    client: "Acme Corporation",
  },
  {
    id: "inventory",
    name: "Inventory",
    risk: "High",
    progress: 30,
    assignedAuditor: { id: "a1", name: "Emma Wilson", avatar: "EW" },
    tasks: [
      { id: "t1", title: "Plan physical inventory", status: "Open" },
      { id: "t2", title: "Test inventory valuation", status: "Open" },
      { id: "t3", title: "Review purchase orders", status: "Open" },
      { id: "t4", title: "Test inventory cutoff", status: "Open" },
      { id: "t5", title: "Review obsolescence", status: "Open" },
      { id: "t6", title: "Test perpetual records", status: "Open" },
      { id: "t7", title: "Review inventory policies", status: "Open" },
      { id: "t8", title: "Test pricing", status: "Open" },
      { id: "t9", title: "Review COGS", status: "Open" },
      { id: "t10", title: "Test adjustments", status: "Open" },
      { id: "t11", title: "Review reserves", status: "Open" },
      { id: "t12", title: "Test controls", status: "Open" },
      { id: "t13", title: "Review aging", status: "Open" },
      { id: "t14", title: "Test completeness", status: "Open" },
      { id: "t15", title: "Review composition", status: "Open" },
    ],
    evidence: [
      { id: "e1", title: "Inventory listing", status: "Open" },
      { id: "e2", title: "Physical count sheets", status: "Open" },
      { id: "e3", title: "Inventory policies", status: "Open" },
      { id: "e4", title: "PO samples", status: "Open" },
      { id: "e5", title: "Cost calculations", status: "Open" },
      { id: "e6", title: "Cutoff analysis", status: "Open" },
      { id: "e7", title: "Obsolescence reserve", status: "Open" },
      { id: "e8", title: "Perpetual records", status: "Open" },
      { id: "e9", title: "Pricing schedules", status: "Open" },
      { id: "e10", title: "COGS analysis", status: "Open" },
      { id: "e11", title: "Reserve calculations", status: "Open" },
      { id: "e12", title: "Control testing", status: "Open" },
      { id: "e13", title: "Aging analysis", status: "Open" },
      { id: "e14", title: "Completeness tests", status: "Open" },
      { id: "e15", title: "Composition review", status: "Open" },
      { id: "e16", title: "Valuation tests", status: "Open" },
      { id: "e17", title: "Inventory samples", status: "Open" },
      { id: "e18", title: "Count instructions", status: "Open" },
    ],
    status: "Planning",
    client: "Acme Corporation",
  },
  {
    id: "fixed-assets",
    name: "Fixed Assets",
    risk: "Medium",
    progress: 62,
    assignedAuditor: { id: "a4", name: "James Rodriguez", avatar: "JR" },
    tasks: [
      { id: "t1", title: "Test additions", status: "In Progress" },
      { id: "t2", title: "Test disposals", status: "Open" },
      { id: "t3", title: "Test depreciation", status: "Open" },
      { id: "t4", title: "Review impairment", status: "Open" },
      { id: "t5", title: "Test allocation", status: "Open" },
    ],
    evidence: [
      { id: "e1", title: "Fixed asset register", status: "In Progress" },
      { id: "e2", title: "Additions documentation", status: "Open" },
      { id: "e3", title: "Disposal records", status: "Open" },
      { id: "e4", title: "Depreciation schedules", status: "Open" },
      { id: "e5", title: "Impairment analysis", status: "Open" },
      { id: "e6", title: "Allocation methodology", status: "Open" },
      { id: "e7", title: "Capital policy", status: "Open" },
      { id: "e8", title: "Asset verification", status: "Open" },
    ],
    status: "In Progress",
    client: "Acme Corporation",
  },
  {
    id: "accounts-receivable",
    name: "Accounts Receivable",
    risk: "Medium",
    progress: 78,
    assignedAuditor: { id: "a2", name: "David Martinez", avatar: "DM" },
    tasks: [
      { id: "t1", title: "Test AR aging", status: "Completed" },
      { id: "t2", title: "Review allowance", status: "Completed" },
    ],
    evidence: [
      { id: "e1", title: "AR aging report", status: "Completed" },
      { id: "e2", title: "Allowance analysis", status: "Completed" },
      { id: "e3", title: "Collection analysis", status: "Open" },
    ],
    status: "Review",
    client: "Acme Corporation",
  },
  {
    id: "accounts-payable",
    name: "Accounts Payable",
    risk: "Low",
    progress: 100,
    assignedAuditor: { id: "a3", name: "Lisa Anderson", avatar: "LA" },
    tasks: [],
    evidence: [],
    status: "Complete",
    client: "Acme Corporation",
  },
  {
    id: "expenses",
    name: "Expenses",
    risk: "Low",
    progress: 55,
    assignedAuditor: { id: "a5", name: "Jennifer Taylor", avatar: "JT" },
    tasks: [
      { id: "t1", title: "Test expense accruals", status: "In Progress" },
      { id: "t2", title: "Review prepaid expenses", status: "Open" },
      { id: "t3", title: "Test allocation", status: "Open" },
      { id: "t4", title: "Review expense policies", status: "Open" },
      { id: "t5", title: "Test approvals", status: "Open" },
      { id: "t6", title: "Review documentation", status: "Open" },
    ],
    evidence: [
      { id: "e1", title: "Expense GL details", status: "In Progress" },
      { id: "e2", title: "Accrual analysis", status: "Open" },
      { id: "e3", title: "Prepaid schedules", status: "Open" },
      { id: "e4", title: "Allocation methodology", status: "Open" },
      { id: "e5", title: "Expense policies", status: "Open" },
      { id: "e6", title: "Approval evidence", status: "Open" },
      { id: "e7", title: "Sample invoices", status: "Open" },
    ],
    status: "In Progress",
    client: "Acme Corporation",
  },
];

export const progressBreakdown: ProgressBreakdown = {
  planning: 15,
  evidence: 58,
  review: 27,
};

export const highRiskAreas: AuditArea[] = auditAreas.filter(
  (area) => area.risk === "High"
);

export const deadlines: Deadline[] = [
  {
    id: 1,
    title: "Revenue Testing Complete",
    date: "2024-08-30",
    daysRemaining: 33,
  },
  {
    id: 2,
    title: "Inventory Count & Reconciliation",
    date: "2024-09-15",
    daysRemaining: 50,
  },
  {
    id: 3,
    title: "Final Audit Report Due",
    date: "2024-12-31",
    daysRemaining: 157,
  },
];

export const activityItems: ActivityItem[] = [
  {
    id: 1,
    user: "Emma Wilson",
    action: "Requested additional supporting documents for Revenue area",
    time: "2 hours ago",
  },
  {
    id: 2,
    user: "David Martinez",
    action: "Completed Cash & Bank reconciliation testing",
    time: "5 hours ago",
  },
  {
    id: 3,
    user: "Lisa Anderson",
    action: "Marked Payroll area as ready for final review",
    time: "1 day ago",
  },
  {
    id: 4,
    user: "Michael Chen",
    action: "Updated engagement timeline and milestones",
    time: "2 days ago",
  },
];
